import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#151c27",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e8e8e8",
        "surface-tint": "#5e5e5e",
        "surface-container-low": "#f3f3f3",
        "on-error": "#ffffff",
        secondary: "#585f6c",
        background: "#f9f9f9",
        "on-secondary-container": "#5e6572",
        "primary-fixed-dim": "#c6c6c6",
        "surface-variant": "#e2e2e2",
        "surface-dim": "#dadada",
        outline: "#7e7576",
        "on-surface-variant": "#4c4546",
        "on-background": "#1b1b1b",
        "primary-fixed": "#e2e2e2",
        "inverse-on-surface": "#f1f1f1",
        "inverse-primary": "#c6c6c6",
        "on-secondary-fixed-variant": "#404754",
        surface: "#f9f9f9",
        "secondary-container": "#dce2f3",
        "inverse-surface": "#303030",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#e2e2e2",
        "on-primary-fixed": "#1b1b1b",
        "surface-bright": "#f9f9f9",
        primary: "#000000",
        "primary-container": "#1b1b1b",
        error: "#ba1a1a",
        "on-primary-container": "#848484",
        "secondary-fixed-dim": "#c0c7d6",
        "outline-variant": "#cfc4c5",
        tertiary: "#000000",
        "tertiary-fixed-dim": "#c6c6c6",
        "on-tertiary-fixed": "#1b1b1b",
        "tertiary-container": "#1b1b1b",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#848484",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#e2e2e2",
        "on-tertiary": "#ffffff",
        "on-surface": "#1b1b1b",
        "on-primary-fixed-variant": "#474747",
        "secondary-fixed": "#dce2f3",
        "surface-container": "#eeeeee",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#474747",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        md: "16px",
        xs: "4px",
        "margin-desktop": "32px",
        base: "4px",
        gutter: "20px",
        sm: "8px",
        lg: "24px",
        xl: "40px",
        "margin-mobile": "16px",
      },
      fontFamily: {
        "numeric-data": ["var(--font-inter)"],
        "body-lg": ["var(--font-inter)"],
        display: ["var(--font-inter)"],
        "headline-md": ["var(--font-inter)"],
        "body-md": ["var(--font-inter)"],
        "label-caps": ["var(--font-inter)"],
        "headline-lg-mobile": ["var(--font-inter)"],
        "headline-lg": ["var(--font-inter)"],
      },
      fontSize: {
        "numeric-data": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" },
        ],
        "body-lg": [
          "16px",
          { lineHeight: "24px", letterSpacing: "0", fontWeight: "400" },
        ],
        display: [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "headline-md": [
          "20px",
          { lineHeight: "28px", letterSpacing: "-0.005em", fontWeight: "500" },
        ],
        "body-md": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0", fontWeight: "400" },
        ],
        "label-caps": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "headline-lg": [
          "30px",
          { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
      },
    },
  },
  plugins: [],
};
export default config;
